scene:
  image_settings:
    width: 2000
    height: 1200
    background_color: [255, 255, 255]

  camera:
    # To see the difference between projections, switch the type below.
    # 'perspective': Objects farther away appear smaller (realistic).
    # 'orthographic': All objects appear at their actual size regardless of depth.
    type: 'perspective'
    position: [150, 0, 500]  # Moved camera back for a clear view
    target: [0, 0, 0]    # Point the camera is looking at
    up: [0, 1, 0]        # Up direction for the camera

    # Perspective-specific settings
    fov: 60

    # Orthographic-specific settings (defines the viewing box in world units)
    ortho_bounds: [-500, 500, -500, 500] # [left, right, bottom, top]

    # Clipping planes (used by both projections)
    near: 0.1
    far: 100

  renderer:
    type: rasterization
    options:
      shading: 'flat' # Options could be 'none', 'flat', 'gouraud', 'phong'

  lights:
    - type: ambient
      color: [255, 255, 255]
      intensity: 0.2
    - type: point
      color: [255, 255, 255]
      intensity: 0.8
      position: [0, 0, 500] # 3D position for future use

  materials:
    black_plastic:
      color: [0, 0, 0]
    red_plastic:
      color: [255, 0, 0]
    blue_plastic:
      color: [0, 0, 255]
    yellow_plastic:
      color: [255, 255, 0]
    green_plastic:
      color: [0, 255, 0]
      # Future properties for shading
      # ambient: [0.1, 0.1, 0.1]
      # diffuse: [0.7, 0.7, 0.7]
      # specular: [0.2, 0.2, 0.2]
      # shininess: 32

  objects:

    - name: test_circle_q1
      type: circle
      material: black_plastic
      center: [300, 200]
      radius: 100
      transformations: []

    - name: test_circle_q2
      type: circle
      material: black_plastic
      center: [300, -200]
      radius: 100
      transformations: []

    - name: test_circle_q3
      type: circle
      material: black_plastic
      center: [-300, -200]
      radius: 100
      transformations: []

    - name: test_circle_q4
      type: circle
      material: black_plastic
      center: [-300, 200]
      radius: 100
      transformations: []
      
    - name: test_line_q1
      type: line
      material: black_plastic
      start: [100, 50]
      end: [500, 200]

    - name: test_line_q2
      type: line
      material: black_plastic
      start: [-100, 50]
      end: [-500, 200]

    - name: test_line_q3
      type: line
      material: black_plastic
      start: [-100, -50]
      end: [-500, -200]

    - name: test_line_q4
      type: line
      material: black_plastic
      start: [100, -50]
      end: [500, -200]

    - name: test_line_clipping
      type: line
      material: black_plastic
      start: [-500, 200]
      end: [-1500, 400]

    - name: test_triangle
      type: triangle
      material: black_plastic
      vertices:
        - [-50, -50]
        - [50, -50]
        - [0, 50]

    - name: test_polygon
      type: polygon
      material: red_plastic
      vertices:
        - [100, 125]
        - [200, 100]
        - [250, 200]
        - [150, 300]
        - [50, 200]

    - name: test_polygon_corner
      type: polygon
      material: red_plastic
      vertices:
        - [75, 300]
        - [100, 100]
        - [300, 100]
        - [325, 300]
        - [200, 150]
        - [75, 300]

    - name: test_triangle_clipping
      type: triangle
      material: red_plastic
      vertices:
        - [500, 300]
        - [1500, 300]
        - [950, 550]

    - name: transformed_triangle
      type: triangle
      material: blue_plastic
      vertices:
        - [-50, -50]
        - [50, -50]
        - [0, 50]
      transform:
        - type: scale
          factor: [1,5]
        - type: rotate
          angle: 90
        - type: translate
          offset: [0, -500]

    - name: my_3d_cube
      type: cube_3d
      material: black_plastic
      center: [0, 0, 0] # Center of the cube in 3D space
      size: 100 # Side length of the cube
      transform:
        - type: rotate_x
          angle: 0
        - type: rotate_y
          angle: 0
        - type: translate_3d
          offset: [-800, 0, 0]
      edges:
        - [0, 1]
        - [1, 2]
        - [2, 3]
        - [3, 0] # Back face
        - [4, 5]
        - [5, 6]
        - [6, 7]
        - [7, 4] # Front face
        - [0, 4]
        - [1, 5]
        - [2, 6]
        - [3, 7] # Connecting edges

    - name: my_3d_cube_x
      type: cube_3d
      material: black_plastic
      center: [0, 0, 0] # Center of the cube in 3D space
      size: 100 # Side length of the cube
      transform:
        - type: rotate_x
          angle: 30
        - type: rotate_y
          angle: 0
        - type: rotate_z
          angle: 0
        - type: translate_3d
          offset: [-400, 0, 0] 
        
      edges:
        - [0, 1]
        - [1, 2]
        - [2, 3]
        - [3, 0] # Back face
        - [4, 5]
        - [5, 6]
        - [6, 7]
        - [7, 4] # Front face
        - [0, 4]
        - [1, 5]
        - [2, 6]
        - [3, 7] # Connecting edges
    - name: my_3d_cube_y
      type: cube_3d
      material: black_plastic
      center: [0, 0, 0] # Center of the cube in 3D space
      size: 5 # Side length of the cube
      transform:
        - type: rotate_x
          angle: 0
        - type: rotate_y
          angle: 30
        - type: rotate_z
          angle: 0
      edges:
        - [0, 1]
        - [1, 2]
        - [2, 3]
        - [3, 0] # Back face
        - [4, 5]
        - [5, 6]
        - [6, 7]
        - [7, 4] # Front face
        - [0, 4]
        - [1, 5]
        - [2, 6]
        - [3, 7] # Connecting edges
    - name: my_3d_cube_z
      type: cube_3d
      material: black_plastic
      center: [0, 0, 0] # Center of the cube in 3D space
      size: 100 # Side length of the cube
      transform:
        - type: rotate_x
          angle: 0
        - type: rotate_y
          angle: 0
        - type: rotate_z
          angle: 30
        - type: translate_3d
          offset: [400, 0, 0]
      edges:
        - [0, 1]
        - [1, 2]
        - [2, 3]
        - [3, 0] # Back face
        - [4, 5]
        - [5, 6]
        - [6, 7]
        - [7, 4] # Front face
        - [0, 4]
        - [1, 5]
        - [2, 6]
        - [3, 7] # Connecting edges

    - name: my_3d_cube_near
      type: cube_3d
      material: blue_plastic
      center: [0, 0, 0] # Moved to the left
      size: 200
      transform:
        - type: rotate_y
          angle: 45
        - type: rotate_z
          angle: 45
      edges:
        - [0, 1]
        - [1, 2]
        - [2, 3]
        - [3, 0] # Back face
        - [4, 5]
        - [5, 6]
        - [6, 7]
        - [7, 4] # Front face
        - [0, 4]
        - [1, 5]
        - [2, 6]
        - [3, 7] # Connecting edges

    - name: my_3d_cube_far
      type: cube_3d
      material: green_plastic
      center: [-400, 0, 200] # Moved to the right and farther back
      size: 200 # Same size
      transform:
        - type: rotate_y
          angle: 30
      edges:
        - [0, 1]
        - [1, 2]
        - [2, 3]
        - [3, 0] # Back face
        - [4, 5]
        - [5, 6]
        - [6, 7]
        - [7, 4] # Front face
        - [0, 4]
        - [1, 5]
        - [2, 6]
        - [3, 7] # Connecting edges