scene:
  image_settings:
    width: 800
    height: 600
    background_color: [0, 0, 0] # Black

  objects:
    main_triangle:
      type: triangle
      vertices:
        - [222, 100]
        - [467, 200]
        - [422, 500]
      colors:
        - [255, 0, 0]
        - [0, 255, 0] 
        - [0, 0, 255] 

    test_circle:
      type: circle
      center: [400, 300]
      radius: 200
      color: [255, 255, 255]
    
    line:
      type: line
      start: [100, 100]
      end: [700, 500]
      color: [255, 255, 255]
